baseURL: https://chaLyoung.github.io/
languageCode: en-us
title: chaLyoung.log
theme: "PaperMod"

params:
    assets:
        disableFingerprinting: true
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: github
          name: github.com
          url: https://github.com/chaLyoung
          weight: 30