baseURL: https://chaLyoung.github.io/
languageCode: en-us
title: chaLyoung.log
theme: "PaperMod"

params:
    assets:
        disableFingerprinting: true
menu:
    main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 10
        - identifier: tags
          name: Pags
          url: /tags/
          weight: 20
        - identifier: github
          name: github.com
          url: https://github.com/chaLyoung
          weight: 30